
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const menu=$('.menu'),navlinks=$('.navlinks'); menu?.addEventListener('click',()=>navlinks.classList.toggle('open'));
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});navlinks?.classList.remove('open')}}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>observer.observe(e));
const hotspots=$$('.hotspot'),ft=$('#feature-title'),fx=$('#feature-text');
const fd={track:{title:'BLE Track Card Module',text:'Bluetooth Low Energy helps a connected smartphone identify the wallet’s last known location.'},buzzer:{title:'Mini Buzzer',text:'A small buzzer provides an audible alert to help locate the wallet when it is nearby.'},battery:{title:'Rechargeable Battery',text:'The concept includes a compact rechargeable battery for the tracking module.'},shell:{title:'Slim Outer Shell',text:'The wallet keeps a familiar everyday form while housing the tracking components inside.'}};
hotspots.forEach(h=>h.addEventListener('click',()=>{hotspots.forEach(x=>x.classList.remove('active'));h.classList.add('active');const d=fd[h.dataset.feature];if(ft)ft.textContent=d.title;if(fx)fx.textContent=d.text}));
const people=$('#people'),total=$('#total');const calc=()=>{const n=Number(people?.value||1),price=Number(total?.dataset.price||96);if(total)total.textContent='RM '+(n*price).toLocaleString('en-MY',{minimumFractionDigits:2})};people?.addEventListener('input',calc);calc();
const locateBtn=$('#locateBtn'),toast=$('.toast');locateBtn?.addEventListener('click',()=>{locateBtn.textContent='SCANNING…';setTimeout(()=>{locateBtn.textContent='FOUND WALLET';if(toast){toast.textContent='TrackCard found nearby • Buzzer activated';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}},1200)});
const modal=$('#demoModal'),demoBtn=$('#demoBtn'),close=$('#closeModal');demoBtn?.addEventListener('click',()=>modal.classList.add('open'));close?.addEventListener('click',()=>modal.classList.remove('open'));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
const year=$('#year');if(year)year.textContent=new Date().getFullYear();
const feedbackForm=$('#feedbackForm'),feedbackSuccess=$('#feedbackSuccess');
feedbackForm?.addEventListener('submit',e=>{e.preventDefault();const f={name:$('#feedbackName')?.value.trim()||'Anonymous',type:$('#feedbackType')?.value||'Other',message:$('#feedbackMessage')?.value.trim()||'',time:new Date().toISOString()};if(!f.message)return;const old=JSON.parse(localStorage.getItem('trackcardFeedback')||'[]');old.push(f);localStorage.setItem('trackcardFeedback',JSON.stringify(old));feedbackForm.reset();if(feedbackSuccess){feedbackSuccess.style.display='block';setTimeout(()=>feedbackSuccess.style.display='none',4500)}});
